server:
  port: 9000
spring:
  application:
    name: order-service
  redis:
    host: 10.102.36.153
    port: 26379
    timeout: 2000
    database: 1
    password: tttt
eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8081/eureka/,http://center2:8082/eureka/
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/auth-service/user/
    client:
      id: client_1
      client-secret: 123456
      access-token-uri: http://localhost:8080/auth-service/oauth/token
      grant-type: client_credentials,password
      scope: server
